import { supabase } from "./supabase.js";
const { data:{ session } } = await supabase.auth.getSession();
if (!session) window.location.replace("./login.html");
const USER = session.user;
const root=document.documentElement;
const $=id=>document.getElementById(id);
let accounts=[], categories=[], transactions=[], reimbursements=[], reimburse_payments=[], ledger_people=[], ledger_entries=[], ledger_payments=[], recurring_rules=[], profile={};
let currentTxnType="expense", currentLedgerType="lent", currentCatType="expense", currentImportKind="transactions";
let importRows=[], importHeaders=[];

const ROUTES={dashboard:{title:"Dashboard",sub:"Your money overview at a glance."},accounts:{title:"Accounts",sub:"Track balances across all accounts."},transactions:{title:"Transactions",sub:"Income, expense, and transfer history."},reimburse:{title:"Reimburse",sub:"Track money others still owe you."},ledger:{title:"Ledger",sub:"Manage long-term borrow and lend."},recurring:{title:"Recurring",sub:"Bills, subscriptions, and reminders."},reports:{title:"Reports",sub:"Monthly trends and category totals."},settings:{title:"Settings",sub:"Profile, categories, and preferences."}};

function toast(msg,d=2600){const el=$("toast");el.textContent=msg;el.classList.remove("hidden");clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.add("hidden"),d)}
function fmt(n,symbol="₹"){return symbol+Number(n||0).toLocaleString("en-IN",{minimumFractionDigits:0,maximumFractionDigits:2})}
function today(){return new Date().toISOString().split("T")[0]}
function openModal(id){$(id).classList.remove("hidden")}
function closeModal(id){$(id).classList.add("hidden")}
function getRoute(){const r=location.hash.replace("#","");return ROUTES[r]?r:"dashboard"}
function parseDate(raw){if(!raw) return today(); const f=$("importDateFormat")?.value||"yyyy-mm-dd"; const v=String(raw).trim(); if(/^\d{4}-\d{2}-\d{2}$/.test(v)) return v; if(f==="dd/mm/yyyy"){const [d,m,y]=v.split(/[\/\-]/); if(y&&m&&d) return `${y}-${m.padStart(2,'0')}-${d.padStart(2,'0')}`;} if(f==="mm/dd/yyyy"){const [m,d,y]=v.split(/[\/\-]/); if(y&&m&&d) return `${y}-${m.padStart(2,'0')}-${d.padStart(2,'0')}`;} return v; }
function dedupeFingerprint(obj){return [obj.date,obj.amount,obj.type,obj.account_id||"",obj.transfer_to_account_id||"",obj.remarks||""].join("|")}

async function loadAll(){
  const uid=USER.id;
  const [{data:ac},{data:ca},{data:tx},{data:rb},{data:rp},{data:lp},{data:le},{data:lpay},{data:rr},{data:pr}] = await Promise.all([
    supabase.from("accounts").select("*").eq("user_id",uid).eq("is_archived",false).order("created_at"),
    supabase.from("categories").select("*").eq("user_id",uid).order("type").order("name"),
    supabase.from("transactions").select("*").eq("user_id",uid).order("date",{ascending:false}).order("created_at",{ascending:false}).limit(2000),
    supabase.from("reimbursements").select("*").eq("user_id",uid).order("created_at",{ascending:false}),
    supabase.from("reimburse_payments").select("*").eq("user_id",uid),
    supabase.from("ledger_people").select("*").eq("user_id",uid).order("person_name"),
    supabase.from("ledger_entries").select("*").eq("user_id",uid).order("date",{ascending:false}),
    supabase.from("ledger_payments").select("*").eq("user_id",uid),
    supabase.from("recurring_rules").select("*").eq("user_id",uid).eq("is_active",true).order("next_due"),
    supabase.from("profiles").select("*").eq("id",uid).single(),
  ]);
  accounts=ac||[]; categories=ca||[]; transactions=tx||[]; reimbursements=rb||[]; reimburse_payments=rp||[]; ledger_people=lp||[]; ledger_entries=le||[]; ledger_payments=lpay||[]; recurring_rules=rr||[]; profile=pr||{};
}
function accountBalance(id){const acc=accounts.find(a=>a.id===id); if(!acc) return 0; let bal=Number(acc.opening_balance||0); transactions.forEach(t=>{ if(t.is_transfer){ if(t.account_id===id) bal-=Number(t.amount); if(t.transfer_to_account_id===id) bal+=Number(t.amount);} else { if(t.account_id!==id) return; if(t.type==="income") bal+=Number(t.amount); if(t.type==="expense") bal-=Number(t.amount);} }); return bal;}
function thisMonthTxns(){const now=new Date();const ym=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}`;return transactions.filter(t=>t.date&&t.date.startsWith(ym))}
function populateAccountSelect(id,ph="Select account"){const sel=$(id); if(!sel) return; sel.innerHTML=`<option value="">${ph}</option>`; accounts.forEach(a=>{const o=document.createElement("option");o.value=a.id;o.textContent=`${a.emoji} ${a.name}`;sel.appendChild(o);});}
function populateCategorySelect(id,type="expense"){const sel=$(id); if(!sel) return; sel.innerHTML='<option value="">No category</option>'; categories.filter(c=>c.type===type).forEach(c=>{const o=document.createElement("option");o.value=c.id;o.textContent=`${c.emoji} ${c.name}`;sel.appendChild(o);});}
function findAccountByName(name){if(!name) return null; const clean=String(name).trim().toLowerCase(); return accounts.find(a=>a.name.trim().toLowerCase()===clean) || accounts.find(a=>a.name.trim().toLowerCase().includes(clean)) || null}
function findCategoryByName(name,type){if(!name) return null; const clean=String(name).trim().toLowerCase(); return categories.find(c=>c.type===type && c.name.trim().toLowerCase()===clean) || categories.find(c=>c.type===type && c.name.trim().toLowerCase().includes(clean)) || null}
function renderProfile(){const name=profile.name||USER.email?.split('@')[0]||'User'; $("userName").textContent=name; $("userEmail").textContent=USER.email||""; $("userAvatar").textContent=name[0].toUpperCase(); if($("settingName")) $("settingName").value=name; if($("settingCurrency")) $("settingCurrency").value=profile.currency||"INR";}
function renderRoute(){const route=getRoute(), meta=ROUTES[route]; $("pageTitle").textContent=meta.title; $("pageSub").textContent=meta.sub; document.querySelectorAll('[data-view]').forEach(el=>el.classList.toggle('active',el.dataset.view===route)); document.querySelectorAll('[data-route]').forEach(el=>el.classList.toggle('active',el.dataset.route===route)); document.body.classList.remove('sidebar-open'); if(route==='dashboard') renderDashboard(); if(route==='accounts') renderAccounts(); if(route==='transactions') renderTransactions(); if(route==='reimburse') renderReimburse(); if(route==='ledger') renderLedger(); if(route==='recurring') renderRecurring(); if(route==='reports') renderReports(); if(route==='settings') renderSettings(); }

function txnHTML(t){
  const cat=categories.find(c=>c.id===t.category_id); const acc=accounts.find(a=>a.id===t.account_id); const to=accounts.find(a=>a.id===t.transfer_to_account_id);
  const icon=t.is_transfer?'🔄':(cat?.emoji||'💸'); const type=t.is_transfer?'transfer':t.type; const label=t.is_transfer?`${acc?.name||'?'} → ${to?.name||'?'}`:(cat?.name||'Uncategorised'); const sub=[acc?.name,t.remarks].filter(Boolean).join(' · '); const amtSign=t.is_transfer?'':(t.type==='income'?'+':'-');
  return `<div class="txn-item"><div class="txn-icon ${type}">${icon}</div><div class="txn-meta"><div class="txn-cat">${label}</div><div class="txn-sub">${sub||''}</div></div><div class="txn-right"><div class="txn-amount ${type==='income'?'green':type==='expense'?'red':'orange'}">${amtSign}${fmt(t.amount)}</div><div class="txn-date">${t.date}</div></div><div class="txn-actions"><button class="icon-action" onclick="editTransaction('${t.id}')">Edit</button><button class="icon-action danger-action" onclick="deleteTransaction('${t.id}')">Delete</button></div></div>`;
}

function renderDashboard(){const total=accounts.reduce((s,a)=>s+accountBalance(a.id),0); const mtx=thisMonthTxns(); const income=mtx.filter(t=>t.type==='income'&&!t.is_transfer).reduce((s,t)=>s+Number(t.amount),0); const expense=mtx.filter(t=>t.type==='expense'&&!t.is_transfer).reduce((s,t)=>s+Number(t.amount),0); const due=reimbursements.filter(r=>r.status!=='settled').reduce((s,r)=>s+(Number(r.total_amount)-Number(r.paid_back)),0); $("kpiBalance").textContent=fmt(total); $("kpiIncome").textContent=fmt(income); $("kpiExpense").textContent=fmt(expense); $("kpiReimburse").textContent=fmt(due); $("kpiAccounts").textContent=`${accounts.length} account${accounts.length!==1?'s':''}`; $("dashRecentList").innerHTML=transactions.slice(0,8).map(txnHTML).join('')||'<div class="empty-state">No transactions yet.</div>'; $("dashAccountsList").innerHTML=accounts.map(a=>`<div class="txn-item"><div class="txn-icon transfer">${a.emoji}</div><div class="txn-meta"><div class="txn-cat">${a.name}</div><div class="txn-sub">${a.type}</div></div><div class="txn-right"><div class="txn-amount">${fmt(accountBalance(a.id))}</div></div></div>`).join('')||'<div class="empty-state">No accounts yet.</div>';}
function renderAccounts(){const list=$("accountsList"); list.innerHTML=accounts.length?accounts.map(a=>`<article class="account-card"><div>${a.emoji}</div><div><strong>${a.name}</strong></div><div>${a.type}</div><div class="account-balance">${fmt(accountBalance(a.id))}</div><div class="account-actions"><button class="btn-sm" onclick="editAccount('${a.id}')">Edit</button><button class="btn-danger" onclick="deleteAccount('${a.id}')">Delete</button></div></article>`).join(''):'<div class="empty-state">No accounts yet.</div>'}
function renderTransactions(){const type=$("txnFilterType").value, accId=$("txnFilterAccount").value, month=$("txnFilterMonth").value; const sel=$("txnFilterAccount"); const prev=sel.value; sel.innerHTML='<option value="">All accounts</option>'; accounts.forEach(a=>{const o=document.createElement('option');o.value=a.id;o.textContent=`${a.emoji} ${a.name}`;sel.appendChild(o)}); sel.value=prev; let list=[...transactions]; if(type) list=list.filter(t=>t.is_transfer?(type==='transfer'):t.type===type); if(accId) list=list.filter(t=>t.account_id===accId||t.transfer_to_account_id===accId); if(month) list=list.filter(t=>t.date&&t.date.startsWith(month)); $("txnList").innerHTML=list.length?list.map(txnHTML).join(''):'<div class="empty-state">No transactions match these filters.</div>'}
function renderReimburse(){const list=$("reimburseList"); list.innerHTML=reimbursements.length?reimbursements.map(r=>{const pct=Math.min(100,Math.round((Number(r.paid_back)/Number(r.total_amount))*100)); const due=Number(r.total_amount)-Number(r.paid_back); const badge=r.status==='settled'?'badge-settled':r.status==='partial'?'badge-partial':'badge-pending'; return `<div class="reimb-item"><div class="reimb-head"><div><div><strong>👤 ${r.person_name}</strong></div><div class="txn-sub">Total: ${fmt(r.total_amount)} · Paid: ${fmt(r.paid_back)} · Due: ${fmt(due)}</div></div><span class="badge ${badge}">${r.status}</span></div><div class="progress-bar-wrap"><div class="progress-bar" style="width:${pct}%"></div></div><div class="reimb-actions">${r.status!=='settled'?`<button class="btn-sm" onclick="openPayback('${r.id}')">Record payback</button>`:''}<button class="btn-danger" onclick="deleteReimburse('${r.id}')">Delete</button></div></div>`}).join(''):'<div class="empty-state">No reimbursements yet.</div>'}
function renderLedger(){const list=$("ledgerList"); list.innerHTML=ledger_people.length?ledger_people.map(p=>{const entries=ledger_entries.filter(e=>e.person_id===p.id); const balance=entries.reduce((s,e)=>s+(e.is_settled?0:(e.type==='lent'?Number(e.amount):-Number(e.amount))),0); return `<div class="ledger-person-card"><div class="lp-head"><div>${p.emoji}</div><div><div><strong>${p.person_name}</strong></div><div class="txn-sub">${p.notes||''}</div></div><div style="margin-left:auto"><div class="lp-balance">${fmt(Math.abs(balance))}</div></div></div><div class="lp-entries">${entries.map(e=>`<div class="le-row${e.is_settled?' le-settled':''}"><span>${e.type==='lent'?'↑ Lent':'↓ Borrowed'}</span><span>${fmt(e.amount)}</span><span>${e.date}</span>${!e.is_settled?`<button class="btn-sm" style="min-height:auto;padding:.2rem .5rem" onclick="settleLedgerEntry('${e.id}')">Settle</button>`:''}</div>`).join('')||'<div class="empty-state" style="padding:1rem">No entries yet.</div>'}</div><div class="row-actions"><button class="btn-sm" onclick="openLedgerEntry('${p.id}')">+ Entry</button><button class="btn-danger" onclick="deleteLedgerPerson('${p.id}')">Delete</button></div></div>`}).join(''):'<div class="empty-state">No ledger entries yet.</div>'}
function renderRecurring(){const list=$("recurringList"); list.innerHTML=recurring_rules.length?recurring_rules.map(r=>`<div class="rec-card"><div><strong>${r.remarks||'Recurring'}</strong></div><div class="txn-sub">${r.frequency} · ${r.next_due}</div><div class="rec-amount ${r.type==='income'?'green':'red'}">${fmt(r.amount)}</div><div class="row-actions"><button class="btn-sm" onclick="bookRecurring('${r.id}')">Book now</button><button class="btn-danger" onclick="deleteRecurring('${r.id}')">Delete</button></div></div>`).join(''):'<div class="empty-state">No recurring rules yet.</div>'}
function renderReports(){const cur=profile.currency||'INR'; const sym=cur==='USD'?'$':cur==='EUR'?'€':cur==='GBP'?'£':'₹'; const mtx=thisMonthTxns(); const income=mtx.filter(t=>t.type==='income'&&!t.is_transfer).reduce((s,t)=>s+Number(t.amount),0); const expense=mtx.filter(t=>t.type==='expense'&&!t.is_transfer).reduce((s,t)=>s+Number(t.amount),0); $("repIncome").textContent=fmt(income,sym); $("repExpense").textContent=fmt(expense,sym); $("repSavings").textContent=fmt(income-expense,sym); const map={}; mtx.filter(t=>t.type==='expense'&&!t.is_transfer).forEach(t=>{const k=t.category_id||'__none'; map[k]=(map[k]||0)+Number(t.amount)}); const total=Object.values(map).reduce((s,v)=>s+v,0)||1; const sorted=Object.entries(map).sort((a,b)=>b[1]-a[1]); $("reportCatList").innerHTML=sorted.length?sorted.map(([cid,amt])=>{const c=categories.find(x=>x.id===cid); const pct=Math.round((amt/total)*100); return `<div class="cat-report-row"><span>${c?.emoji||'📂'} ${c?.name||'Other'}</span><div class="cat-bar-wrap" style="flex:1"><div class="cat-bar" style="width:${pct}%;background:${c?.color||'var(--color-primary)'}"></div></div><span>${fmt(amt,sym)}</span></div>`}).join(''):'<div class="empty-state">No expense data this month.</div>'}
function renderSettings(){renderProfile(); $("categoryList").innerHTML=categories.length?categories.map(c=>`<div class="cat-row"><span>${c.emoji}</span><span style="flex:1">${c.name}</span><span>${c.type}</span>${!c.is_default?`<button class="btn-danger" style="min-height:auto;padding:.2rem .5rem" onclick="deleteCat('${c.id}')">✕</button>`:''}</div>`).join(''):'<div class="empty-state">No categories.</div>'}

window.editAccount=function(id){const a=accounts.find(x=>x.id===id); if(!a) return; $("accountId").value=a.id; $("accountEmoji").value=a.emoji; $("accountName").value=a.name; $("accountType").value=a.type; $("accountBalance").value=a.opening_balance; $("accountModalTitle").textContent='Edit Account'; openModal('accountModal')}
window.deleteAccount=async function(id){if(!confirm('Delete this account?')) return; const{error}=await supabase.from('accounts').delete().eq('id',id); if(error) return toast('❌ '+error.message); await loadAll(); renderAccounts(); renderDashboard(); toast('🗑️ Account deleted')}
window.editTransaction=function(id){const t=transactions.find(x=>x.id===id); if(!t) return; $("txnId").value=t.id; $("txnAmount").value=t.amount; $("txnDate").value=t.date; $("txnRemarks").value=t.remarks||''; populateAccountSelect('txnAccount'); populateAccountSelect('txnTransferTo','Transfer to…'); currentTxnType=t.is_transfer?'transfer':t.type; document.querySelectorAll('#txnTypeTabs .type-tab').forEach(b=>b.classList.toggle('active',b.dataset.type===currentTxnType)); $("txnTransferToField").style.display=currentTxnType==='transfer'?'':'none'; $("txnCategoryField").style.display=currentTxnType==='transfer'?'none':''; populateCategorySelect('txnCategory', currentTxnType==='transfer'?'expense':currentTxnType); $("txnAccount").value=t.account_id||''; $("txnTransferTo").value=t.transfer_to_account_id||''; $("txnCategory").value=t.category_id||''; $("txnModalTitle").textContent='Edit Transaction'; openModal('txnModal')}
window.deleteTransaction=async function(id){if(!confirm('Delete this transaction?')) return; const{error}=await supabase.from('transactions').delete().eq('id',id); if(error) return toast('❌ '+error.message); await loadAll(); renderTransactions(); renderDashboard(); toast('🗑️ Transaction deleted')}
window.openPayback=function(id){$("paybackReimburseId").value=id; $("paybackAmount").value=''; $("paybackDate").value=today(); $("paybackRemarks").value=''; populateAccountSelect('paybackAccount','Received into…'); openModal('paybackModal')}
window.deleteReimburse=async function(id){if(!confirm('Delete this reimbursement?')) return; const{error}=await supabase.from('reimbursements').delete().eq('id',id); if(error) return toast('❌ '+error.message); await loadAll(); renderReimburse(); renderDashboard(); toast('🗑️ Deleted')}
window.openLedgerEntry=function(personId){$("ledgerEntryPersonId").value=personId; $("ledgerEntryAmount").value=''; $("ledgerEntryDate").value=today(); $("ledgerEntryRemarks").value=''; currentLedgerType='lent'; document.querySelectorAll('[data-ledger-type]').forEach(b=>b.classList.toggle('active',b.dataset.ledgerType==='lent')); openModal('ledgerEntryModal')}
window.settleLedgerEntry=async function(id){await supabase.from('ledger_entries').update({is_settled:true}).eq('id',id); await loadAll(); renderLedger(); toast('✅ Settled')}
window.deleteLedgerPerson=async function(id){if(!confirm('Delete this person?')) return; await supabase.from('ledger_people').delete().eq('id',id); await loadAll(); renderLedger(); toast('🗑️ Deleted')}
window.bookRecurring=async function(id){const r=recurring_rules.find(x=>x.id===id); if(!r) return; await supabase.from('transactions').insert({user_id:USER.id,account_id:r.account_id,category_id:r.category_id,amount:r.amount,type:r.type,date:today(),remarks:r.remarks||'Recurring',is_transfer:false}); const d=new Date(r.next_due); if(r.frequency==='daily') d.setDate(d.getDate()+1); if(r.frequency==='weekly') d.setDate(d.getDate()+7); if(r.frequency==='monthly') d.setMonth(d.getMonth()+1); if(r.frequency==='yearly') d.setFullYear(d.getFullYear()+1); await supabase.from('recurring_rules').update({next_due:d.toISOString().split('T')[0]}).eq('id',id); await loadAll(); renderRecurring(); renderDashboard(); toast('✅ Booked')}
window.deleteRecurring=async function(id){if(!confirm('Delete this recurring rule?')) return; await supabase.from('recurring_rules').delete().eq('id',id); await loadAll(); renderRecurring(); toast('🗑️ Deleted')}
window.deleteCat=async function(id){if(!confirm('Delete this category?')) return; await supabase.from('categories').delete().eq('id',id); await loadAll(); renderSettings(); toast('🗑️ Deleted')}

$("menuBtn").addEventListener('click',()=>document.body.classList.toggle('sidebar-open')); $("sidebarOverlay").addEventListener('click',()=>document.body.classList.remove('sidebar-open')); window.addEventListener('hashchange',renderRoute);
$("themeBtn").addEventListener('click',()=>root.setAttribute('data-theme', root.getAttribute('data-theme')==='dark'?'light':'dark'));
document.querySelectorAll('[data-close]').forEach(btn=>btn.addEventListener('click',()=>closeModal(btn.dataset.close)));
document.querySelectorAll('.modal-backdrop').forEach(bd=>bd.addEventListener('click',e=>{if(e.target===bd) closeModal(bd.id)}));
$("logoutBtn").addEventListener('click',async()=>{await supabase.auth.signOut(); window.location.replace('./login.html')});
$("saveProfileBtn").addEventListener('click',async()=>{const name=$("settingName").value.trim(), currency=$("settingCurrency").value; if(!name) return toast('Enter a name'); const {error}=await supabase.from('profiles').upsert({id:USER.id,name,currency},{onConflict:'id'}); if(error) return toast('❌ '+error.message); profile={...profile,name,currency}; renderProfile(); toast('✅ Profile saved')});

$("addAccountBtn").addEventListener('click',()=>{$("accountId").value=''; $("accountEmoji").value='💳'; $("accountName").value=''; $("accountType").value='bank'; $("accountBalance").value='0'; $("accountModalTitle").textContent='New Account'; openModal('accountModal')});
$("saveAccountBtn").addEventListener('click',async()=>{const id=$("accountId").value, emoji=$("accountEmoji").value.trim()||'💳', name=$("accountName").value.trim(), type=$("accountType").value, opening_balance=parseFloat($("accountBalance").value)||0; if(!name) return toast('Enter account name'); const row={user_id:USER.id,emoji,name,type,opening_balance}; const result=id?await supabase.from('accounts').update(row).eq('id',id):await supabase.from('accounts').insert(row); if(result.error) return toast('❌ '+result.error.message); closeModal('accountModal'); await loadAll(); renderAccounts(); renderDashboard(); toast(id?'✅ Account updated':'✅ Account added')});

function openTxnModal(){ $("txnId").value=''; $("txnAmount").value=''; $("txnRemarks").value=''; $("txnDate").value=today(); currentTxnType='expense'; populateAccountSelect('txnAccount'); populateAccountSelect('txnTransferTo','Transfer to…'); populateCategorySelect('txnCategory','expense'); $("txnTransferToField").style.display='none'; $("txnCategoryField").style.display=''; document.querySelectorAll('#txnTypeTabs .type-tab').forEach(b=>b.classList.toggle('active',b.dataset.type==='expense')); $("txnModalTitle").textContent='Add Transaction'; openModal('txnModal')}
$("addTxnBtn").addEventListener('click',openTxnModal); $("quickAddBtn").addEventListener('click',openTxnModal); $("fabBtn").addEventListener('click',openTxnModal);
document.querySelectorAll('#txnTypeTabs .type-tab').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('#txnTypeTabs .type-tab').forEach(b=>b.classList.remove('active')); btn.classList.add('active'); currentTxnType=btn.dataset.type; const transfer=currentTxnType==='transfer'; $("txnTransferToField").style.display=transfer?'':'none'; $("txnCategoryField").style.display=transfer?'none':''; if(!transfer) populateCategorySelect('txnCategory',currentTxnType)}));
$("saveTxnBtn").addEventListener('click',async()=>{const id=$("txnId").value, amount=parseFloat($("txnAmount").value), account_id=$("txnAccount").value, date=$("txnDate").value, remarks=$("txnRemarks").value.trim(), category_id=$("txnCategory").value||null, transfer_to=$("txnTransferTo").value||null; if(!amount||amount<=0) return toast('Enter valid amount'); if(!account_id) return toast('Select account'); if(!date) return toast('Pick date'); if(currentTxnType==='transfer' && !transfer_to) return toast('Select destination account'); if(currentTxnType==='transfer' && transfer_to===account_id) return toast('Source and destination cannot be same'); const row={user_id:USER.id,account_id,category_id:currentTxnType==='transfer'?null:category_id,amount,date,remarks,type:currentTxnType==='transfer'?'transfer':currentTxnType,is_transfer:currentTxnType==='transfer',transfer_to_account_id:currentTxnType==='transfer'?transfer_to:null}; const result=id?await supabase.from('transactions').update(row).eq('id',id):await supabase.from('transactions').insert(row); if(result.error) return toast('❌ '+result.error.message); closeModal('txnModal'); await loadAll(); renderTransactions(); renderDashboard(); toast(id?'✅ Transaction updated':'✅ Transaction saved')});
["txnFilterType","txnFilterAccount","txnFilterMonth"].forEach(id=>$(id).addEventListener('change',renderTransactions));

$("addReimburseBtn").addEventListener('click',()=>{$("reimbPersonName").value=''; $("reimbAmount").value=''; $("reimbRemarks").value=''; $("reimbDate").value=today(); populateAccountSelect('reimbAccount'); openModal('reimburseModal')});
$("saveReimburseBtn").addEventListener('click',async()=>{const person_name=$("reimbPersonName").value.trim(), total_amount=parseFloat($("reimbAmount").value), account_id=$("reimbAccount").value, date=$("reimbDate").value, remarks=$("reimbRemarks").value.trim(); if(!person_name) return toast('Enter person name'); if(!total_amount||total_amount<=0) return toast('Enter valid amount'); if(!account_id) return toast('Select account'); const {data:rb,error:re}=await supabase.from('reimbursements').insert({user_id:USER.id,person_name,total_amount,paid_back:0,status:'pending'}).select().single(); if(re) return toast('❌ '+re.message); await supabase.from('transactions').insert({user_id:USER.id,account_id,amount:total_amount,type:'expense',date,remarks:remarks||`Reimburse: ${person_name}`,is_transfer:false,reimburse_id:rb.id}); closeModal('reimburseModal'); await loadAll(); renderReimburse(); renderDashboard(); toast('✅ Reimbursement added')});
$("savePaybackBtn").addEventListener('click',async()=>{const reimburse_id=$("paybackReimburseId").value, amount=parseFloat($("paybackAmount").value), account_id=$("paybackAccount").value, date=$("paybackDate").value, remarks=$("paybackRemarks").value.trim(); if(!amount||amount<=0) return toast('Enter amount'); if(!account_id) return toast('Select account'); const rb=reimbursements.find(r=>r.id===reimburse_id); const newPaid=Number(rb.paid_back)+amount; const status=newPaid>=Number(rb.total_amount)?'settled':'partial'; await supabase.from('reimburse_payments').insert({user_id:USER.id,reimburse_id,amount,account_id,date,remarks}); await supabase.from('reimbursements').update({paid_back:newPaid,status}).eq('id',reimburse_id); await supabase.from('transactions').insert({user_id:USER.id,account_id,amount,type:'income',date,remarks:remarks||`Payback from ${rb.person_name}`,is_transfer:false}); closeModal('paybackModal'); await loadAll(); renderReimburse(); renderDashboard(); toast('✅ Payback recorded')});

$("addLedgerPersonBtn").addEventListener('click',()=>{$("ledgerEmoji").value='🧑'; $("ledgerPersonName").value=''; $("ledgerNotes").value=''; openModal('ledgerModal')});
$("saveLedgerPersonBtn").addEventListener('click',async()=>{const person_name=$("ledgerPersonName").value.trim(), emoji=$("ledgerEmoji").value.trim()||'🧑', notes=$("ledgerNotes").value.trim(); if(!person_name) return toast('Enter name'); const {error}=await supabase.from('ledger_people').insert({user_id:USER.id,person_name,emoji,notes}); if(error) return toast('❌ '+error.message); closeModal('ledgerModal'); await loadAll(); renderLedger(); toast('✅ Person added')});
document.querySelectorAll('[data-ledger-type]').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('[data-ledger-type]').forEach(b=>b.classList.remove('active')); btn.classList.add('active'); currentLedgerType=btn.dataset.ledgerType}));
$("saveLedgerEntryBtn").addEventListener('click',async()=>{const person_id=$("ledgerEntryPersonId").value, amount=parseFloat($("ledgerEntryAmount").value), date=$("ledgerEntryDate").value, remarks=$("ledgerEntryRemarks").value.trim(); if(!amount||amount<=0) return toast('Enter amount'); const {error}=await supabase.from('ledger_entries').insert({user_id:USER.id,person_id,amount,type:currentLedgerType,date,remarks,is_settled:false}); if(error) return toast('❌ '+error.message); closeModal('ledgerEntryModal'); await loadAll(); renderLedger(); toast('✅ Entry added')});

$("addRecurringBtn").addEventListener('click',()=>{$("recurringRemarks").value=''; $("recurringAmount").value=''; $("recurringNextDue").value=today(); $("recurringFrequency").value='monthly'; populateAccountSelect('recurringAccount'); populateCategorySelect('recurringCategory','expense'); document.querySelectorAll('[data-rtype]').forEach(b=>b.classList.toggle('active',b.dataset.rtype==='expense')); openModal('recurringModal')});
document.querySelectorAll('[data-rtype]').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('[data-rtype]').forEach(b=>b.classList.remove('active')); btn.classList.add('active'); populateCategorySelect('recurringCategory',btn.dataset.rtype)}));
$("saveRecurringBtn").addEventListener('click',async()=>{const remarks=$("recurringRemarks").value.trim(), amount=parseFloat($("recurringAmount").value), account_id=$("recurringAccount").value, category_id=$("recurringCategory").value||null, frequency=$("recurringFrequency").value, next_due=$("recurringNextDue").value, type=document.querySelector('[data-rtype].active')?.dataset.rtype||'expense'; if(!amount||amount<=0) return toast('Enter amount'); if(!account_id) return toast('Select account'); if(!next_due) return toast('Set due date'); const {error}=await supabase.from('recurring_rules').insert({user_id:USER.id,account_id,category_id,amount,type,frequency,next_due,remarks,is_active:true}); if(error) return toast('❌ '+error.message); closeModal('recurringModal'); await loadAll(); renderRecurring(); toast('✅ Rule saved')});

$("addCategoryBtn").addEventListener('click',()=>{$("catEmoji").value='📂'; $("catName").value=''; currentCatType='expense'; document.querySelectorAll('[data-ctype]').forEach(b=>b.classList.toggle('active',b.dataset.ctype==='expense')); openModal('categoryModal')});
document.querySelectorAll('[data-ctype]').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('[data-ctype]').forEach(b=>b.classList.remove('active')); btn.classList.add('active'); currentCatType=btn.dataset.ctype}));
$("saveCategoryBtn").addEventListener('click',async()=>{const emoji=$("catEmoji").value.trim()||'📂', name=$("catName").value.trim(); if(!name) return toast('Enter category name'); const {error}=await supabase.from('categories').insert({user_id:USER.id,name,emoji,type:currentCatType,color:'#01696f',is_default:false}); if(error) return toast('❌ '+error.message); closeModal('categoryModal'); await loadAll(); renderSettings(); toast('✅ Category added')});

$("exportCsvBtn").addEventListener('click',()=>{const header='Date,Type,Amount,Category,Account,Remarks'; const rows=transactions.map(t=>{const cat=categories.find(c=>c.id===t.category_id); const acc=accounts.find(a=>a.id===t.account_id); return [t.date,t.type,t.amount,cat?.name||'',acc?.name||'',JSON.stringify(t.remarks||'')].join(',')}); const csv=[header,...rows].join('\n'); const a=document.createElement('a'); a.href='data:text/csv;charset=utf-8,'+encodeURIComponent(csv); a.download=`flowledger_export_${today()}.csv`; a.click(); toast('✅ CSV exported')});

// IMPORT
function expectedFields(kind){ if(kind==='transactions') return ['date','amount','type','category','account','note']; if(kind==='transfers') return ['date','amount','from_account','to_account','note']; return ['date','original_amount','reimbursed','pending','status','category','paid_from_account','refund_to_account','note','Person_name']; }
function parseCsv(text, delimiter){ const rows=[]; let row=[], cell='', q=false; for(let i=0;i<text.length;i++){const ch=text[i], nx=text[i+1]; if(ch==='"'){ if(q && nx==='"'){ cell+='"'; i++; } else q=!q; } else if(ch===delimiter && !q){ row.push(cell); cell=''; } else if((ch==='\n' || ch==='\r') && !q){ if(ch==='\r' && nx==='\n') i++; row.push(cell); rows.push(row); row=[]; cell=''; } else cell+=ch; } if(cell.length || row.length){ row.push(cell); rows.push(row);} return rows.filter(r=>r.some(v=>String(v).trim()!=='')); }
function buildMappingGrid(){ const box=$("mappingGrid"); const fields=expectedFields(currentImportKind); box.innerHTML=''; fields.forEach(f=>{ const card=document.createElement('div'); card.className='mapping-card'; const options=['<option value="">-- ignore --</option>', ...importHeaders.map(h=>`<option value="${h}">${h}</option>`)].join(''); card.innerHTML=`<label>${f}</label><select class="input import-map" data-target="${f}">${options}</select>`; box.appendChild(card); }); autoMapFields(); }
function autoMapFields(){ document.querySelectorAll('.import-map').forEach(sel=>{ const target=sel.dataset.target.toLowerCase(); const match=importHeaders.find(h=>h.trim().toLowerCase()===target) || importHeaders.find(h=>h.trim().toLowerCase().includes(target)); if(match) sel.value=match; }); }
function previewTable(rows){ if(!rows.length) return 'No rows found.'; const head=importHeaders.length?importHeaders:rows[0].map((_,i)=>`Column ${i+1}`); const body=rows.slice(0,8).map(r=>`<tr>${head.map((_,i)=>`<td>${(r[i]??'').replaceAll('<','&lt;')}</td>`).join('')}</tr>`).join(''); return `<table class="mini-preview-table"><thead><tr>${head.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${body}</tbody></table>`; }
function currentMapping(){ const map={}; document.querySelectorAll('.import-map').forEach(sel=>{ if(sel.value) map[sel.dataset.target]=sel.value; }); return map; }
async function doPreview(){ const file=$("importFile").files[0]; if(!file) return toast('Choose a CSV file'); const delimiter=$("importDelimiter").value==='\t'?'\t':$("importDelimiter").value; const skipStart=Number($("importSkipStart").value||0), skipEnd=Number($("importSkipEnd").value||0), hasHeader=$("importHasHeader").checked; const text=await file.text(); let rows=parseCsv(text, delimiter).slice(skipStart); if(skipEnd>0) rows=rows.slice(0, Math.max(0, rows.length-skipEnd)); if(!rows.length){ $("importPreview").textContent='No rows found after skipping lines.'; return; } importHeaders=hasHeader?rows[0].map(v=>String(v).trim()):rows[0].map((_,i)=>`Column ${i+1}`); importRows=hasHeader?rows.slice(1):rows; $("importPreview").innerHTML=previewTable(importRows); buildMappingGrid(); toast(`Preview loaded: ${importRows.length} rows`); }
async function runImport(){ if(!importRows.length) return toast('Preview the CSV first'); const map=currentMapping(); const merge=$("importMergeExisting").checked, clearBefore=$("importClearBefore").checked, flip=$("importFlipAmount").checked, split=$("importSplitAmount").checked, useType=$("importUseTypeColumn").checked; if(clearBefore){ if(currentImportKind==='transactions' || currentImportKind==='transfers') await supabase.from('transactions').delete().eq('user_id',USER.id); if(currentImportKind==='reimburse') await supabase.from('reimbursements').delete().eq('user_id',USER.id); }
  const existingFp=new Set(transactions.map(dedupeFingerprint)); let inserted=0, skipped=0;
  if(currentImportKind==='transactions'){
    const payload=[];
    for(const row of importRows){ const obj=Object.fromEntries(importHeaders.map((h,i)=>[h,row[i]??''])); let amount=Number(obj[map.amount]||0); if(flip) amount=-amount; amount=Math.abs(amount); if(!amount) { skipped++; continue; } let type='expense'; if(useType && map.type){ const raw=String(obj[map.type]||'').trim().toLowerCase(); type=raw.includes('income')||raw.includes('inflow')? 'income':'expense'; } const acc=findAccountByName(obj[map.account]); if(!acc){ skipped++; continue; } const cat=findCategoryByName(obj[map.category], type); const item={user_id:USER.id,date:parseDate(obj[map.date]),amount,type,category_id:cat?.id||null,account_id:acc.id,remarks:obj[map.note]||'',is_transfer:false,transfer_to_account_id:null}; const fp=dedupeFingerprint(item); if(merge && existingFp.has(fp)){ skipped++; continue; } existingFp.add(fp); payload.push(item); }
    if(payload.length){ const {error}=await supabase.from('transactions').insert(payload); if(error) return toast('❌ '+error.message); inserted=payload.length; }
  }
  if(currentImportKind==='transfers'){
    const payload=[];
    for(const row of importRows){ const obj=Object.fromEntries(importHeaders.map((h,i)=>[h,row[i]??''])); let amount=Math.abs(Number(obj[map.amount]||0)); if(flip) amount=Math.abs(-amount); if(!amount){ skipped++; continue; } const from=findAccountByName(obj[map.from_account]); const to=findAccountByName(obj[map.to_account]); if(!from||!to||from.id===to.id){ skipped++; continue; } const item={user_id:USER.id,date:parseDate(obj[map.date]),amount,type:'transfer',category_id:null,account_id:from.id,remarks:obj[map.note]||'',is_transfer:true,transfer_to_account_id:to.id}; const fp=dedupeFingerprint(item); if(merge && existingFp.has(fp)){ skipped++; continue; } existingFp.add(fp); payload.push(item); }
    if(payload.length){ const {error}=await supabase.from('transactions').insert(payload); if(error) return toast('❌ '+error.message); inserted=payload.length; }
  }
  if(currentImportKind==='reimburse'){
    for(const row of importRows){ const obj=Object.fromEntries(importHeaders.map((h,i)=>[h,row[i]??''])); const person=(obj[map.Person_name]||obj[map.person_name]||'').trim(); const total_amount=Number(obj[map.original_amount]||0); const paid_back=Math.abs(Number(obj[map.reimbursed]||0)); if(!person||!total_amount){ skipped++; continue; } const pending=Number(obj[map.pending]||Math.max(0,total_amount-paid_back)); const rawStatus=String(obj[map.status]||'').toLowerCase(); const status=pending<=0?'settled':paid_back>0?'partial':(rawStatus.includes('pend')?'pending':'partial'); const {data:rb,error}=await supabase.from('reimbursements').insert({user_id:USER.id,person_name:person,total_amount,paid_back,status}).select().single(); if(error){ skipped++; continue; } inserted++; const paidFrom=findAccountByName(obj[map.paid_from_account]); const refundTo=findAccountByName(obj[map.refund_to_account]); const note=obj[map.note]||''; if(paidFrom){ await supabase.from('transactions').insert({user_id:USER.id,account_id:paidFrom.id,amount:total_amount,type:'expense',date:parseDate(obj[map.date]),remarks:note||`Imported reimburse: ${person}`,is_transfer:false,reimburse_id:rb.id}); }
      if(paid_back>0 && refundTo){ await supabase.from('reimburse_payments').insert({user_id:USER.id,reimburse_id:rb.id,amount:paid_back,account_id:refundTo.id,date:parseDate(obj[map.date]),remarks:`Imported payback: ${note}`}); await supabase.from('transactions').insert({user_id:USER.id,account_id:refundTo.id,amount:paid_back,type:'income',date:parseDate(obj[map.date]),remarks:`Imported payback from ${person}`,is_transfer:false}); }
    }
  }
  await loadAll(); renderRoute(); closeModal('importModal'); toast(`✅ Imported ${inserted} rows, skipped ${skipped}`);
}
$("previewImportBtn").addEventListener('click',doPreview); $("runImportBtn").addEventListener('click',runImport);
document.querySelectorAll('[data-import-kind]').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('[data-import-kind]').forEach(b=>b.classList.remove('active')); btn.classList.add('active'); currentImportKind=btn.dataset.importKind; buildMappingGrid(); }));
$("openTxnImportBtn").addEventListener('click',()=>{ currentImportKind='transactions'; document.querySelectorAll('[data-import-kind]').forEach(b=>b.classList.toggle('active',b.dataset.importKind==='transactions')); importRows=[]; importHeaders=[]; $("importPreview").textContent='Upload a CSV to preview rows.'; $("mappingGrid").innerHTML=''; openModal('importModal'); });
$("openReimburseImportBtn").addEventListener('click',()=>{ currentImportKind='reimburse'; document.querySelectorAll('[data-import-kind]').forEach(b=>b.classList.toggle('active',b.dataset.importKind==='reimburse')); importRows=[]; importHeaders=[]; $("importPreview").textContent='Upload a CSV to preview rows.'; $("mappingGrid").innerHTML=''; openModal('importModal'); });

(async()=>{ await loadAll(); renderProfile(); populateAccountSelect('txnAccount'); populateAccountSelect('txnTransferTo'); populateCategorySelect('txnCategory','expense'); renderRoute(); })();
